"""email column to post

Revision ID: 7410a29233af
Revises: 
Create Date: 2022-12-29 15:06:44.293449

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7410a29233af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('email', sa.String(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['email'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'email')
    # ### end Alembic commands ###
