"""email column to post_updated

Revision ID: 9f60e961e9d5
Revises: 7410a29233af
Create Date: 2022-12-29 15:10:52.237173

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9f60e961e9d5'
down_revision = '7410a29233af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_email_fkey', 'posts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('posts_email_fkey', 'posts', 'users', ['email'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###
