"""update

Revision ID: d445e9e665ca
Revises: c107c3387e7a
Create Date: 2023-01-02 15:33:11.077892

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd445e9e665ca'
down_revision = 'c107c3387e7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('profile_pics', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pics')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
